
export const mlbVenueTimezones = {
  'Chase Field': 'America/Phoenix',
  'Truist Park': 'America/New_York',
  'Oriole Park at Camden Yards': 'America/New_York',
  'Fenway Park': 'America/New_York',
  'Wrigley Field': 'America/Chicago',
  'Guaranteed Rate Field': 'America/Chicago',
  'Great American Ball Park': 'America/New_York',
  'Progressive Field': 'America/New_York',
  'Coors Field': 'America/Denver',
  'Comerica Park': 'America/Detroit',
  'Minute Maid Park': 'America/Chicago',
  'Kauffman Stadium': 'America/Chicago',
  'Angel Stadium': 'America/Los_Angeles',
  'Dodger Stadium': 'America/Los_Angeles',
  'loanDepot park': 'America/New_York',
  'American Family Field': 'America/Chicago',
  'Target Field': 'America/Chicago',
  'Citi Field': 'America/New_York',
  'Yankee Stadium': 'America/New_York',
  'Oakland Coliseum': 'America/Los_Angeles',
  'Citizens Bank Park': 'America/New_York',
  'PNC Park': 'America/New_York',
  'Petco Park': 'America/Los_Angeles',
  'Oracle Park': 'America/Los_Angeles',
  'T-Mobile Park': 'America/Los_Angeles',
  'Busch Stadium': 'America/Chicago',
  'Tropicana Field': 'America/New_York',
  'Globe Life Field': 'America/Chicago',
  'Rogers Centre': 'America/Toronto',
  'Nationals Park': 'America/New_York',
};